// 调用 wasm-pack 构建 crates/fbx-wasm，把生成的 .wasm 以 base64 内联到 src/wasm/inline.ts
//
// 用法：
//   pnpm build:wasm
//
// 需要本机已装 Rust 工具链（wasm32-unknown-unknown target）。
// Windows 上如使用 MSVC toolchain 缺失 link.exe 时，可临时导出
// `RUSTUP_TOOLCHAIN=stable-x86_64-pc-windows-gnu`。

import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(scriptDir, '..')
const cratePath = join(repoRoot, 'crates', 'fbx-wasm')
const outDir = join(repoRoot, 'src', 'wasm', 'pkg')
const inlinePath = join(repoRoot, 'src', 'wasm', 'inline.ts')

const binName = process.platform === 'win32' ? 'wasm-pack.cmd' : 'wasm-pack'
const wasmPack = join(repoRoot, 'node_modules', '.bin', binName)
const args = [
  'build',
  '--target',
  'web',
  '--release',
  cratePath,
  '--out-dir',
  outDir,
]

console.log(`> ${wasmPack} ${args.join(' ')}`)
const result = spawnSync(wasmPack, args, {
  stdio: 'inherit',
  cwd: repoRoot,
  shell: process.platform === 'win32',
})
if (result.status !== 0) {
  process.exit(result.status ?? 1)
}

// wasm-pack writes pkg/.gitignore with `*`, which would hide committed artifacts.
rmSync(join(outDir, '.gitignore'), { force: true })

const wasmPath = join(outDir, 'fbx_wasm_bg.wasm')
const wasmBytes = readFileSync(wasmPath)
const base64 = wasmBytes.toString('base64')

mkdirSync(dirname(inlinePath), { recursive: true })

const banner = `// AUTO-GENERATED by scripts/build-wasm.mjs. Do not edit by hand.
// Regenerate with \`pnpm build:wasm\`.
`
writeFileSync(
  inlinePath,
  `${banner}\nexport const WASM_BYTE_LENGTH = ${wasmBytes.length}\n\nexport const WASM_BASE64 =\n  '${base64}'\n`,
)

console.log(`\nwrote ${inlinePath} (${wasmBytes.length} bytes -> ${base64.length} base64 chars)`)
